[services.backend]
root = ".r"
buildCommand = "cd apps && npm ci && npm run build:web --omit=dev"
startCommand = "npm start"

[deploy]
branch = "main"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"

