[services.backend]
root = "."
buildCommand = "npm ci --omit=dev && npm run -w apps/web build && npm run -w apps/server build"
startCommand = "npm start"

[deploy]
branch = "main"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

