[services.backend]
root = "server"
buildCommand = "cd apps && npm ci && npm run build:web --omit=dev"
startCommand = "npm start"

[deploy]
branch = "main"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

