[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --no-audit --no-fund && npm run build:client"


[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "onFailure"
restartPolicyMaxRetries = 3


[env]
NODE_ENV = "production"
