[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --no-audit --no-fund && npm run build:client"

[deploy]
startCommand = "node server/src/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyType = "onFailure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
