[deploy]
startCommand = "bash -lc 'cd server && npm install --omit=dev --no-audit --no-fund && npm start'"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --no-audit --no-fund && npm run build:client"
